### ISSUE TITLE
WEBGL 各向异性过滤

### ISSUE THREAD

**Issue by kaisersd** [feng3d-labs/feng3d-ts#49]
参考

http://ife.baidu.com/note/detail/id/663

anisotropy：各向异性过滤。使用各向异性过滤能够使纹理的效果更好，但是会消耗更多的内存、CPU、GPU时间。

**Comment by wardenfeng** [comment]
@kaisersd 

            //材质
            var textureMaterial = model.material = new StandardMaterial();
            textureMaterial.diffuseMethod.difuseTexture.url = 'resources/m.png';
//设置各向异性过滤
            textureMaterial.diffuseMethod.difuseTexture.anisotropy = 16;
