### ISSUE TITLE
支持透明贴图和物件透明度

### ISSUE THREAD

**Issue by kaisersd** [feng3d-labs/feng3d-ts#51]
Object3D的透明度

**Comment by wardenfeng** [comment]
完全透明：
```
(property) feng3d.DiffuseMethod.alphaThreshold: number
```
透明阈值，透明度小于该值的像素被片段着色器丢弃
示例
```
            var textureMaterial = model.material = new StandardMaterial();
            textureMaterial.diffuseMethod.difuseTexture.url = 'resources/m.png';
            textureMaterial.diffuseMethod.alphaThreshold = 0.1;
```
半透明：
···
export class Material
        /**
         * 是否开启混合
         */
        public enableBlend = false;

        /**
         * 混合方程
         */
        public blendEquation = GL.FUNC_ADD;

        /**
         * 源混合因子
         */
        public sfactor = GL.ONE;

        /**
         * 目标混合因子
         */
        public dfactor = GL.ZERO;
···
